openthread/ot-commissioner

.codecov.yml, .travis/after_success.sh, .travis/script.sh, README.md, src/CMakeLists.txt, tests/CMakeLists.txt
This PR uploads coverage to https://codecov.io.
=> [tests] update coverage

.gitignore, include/commissioner/border_agent.hpp, include/commissioner/commissioner.hpp, include/commissioner/defines.hpp, include/commissioner/network_data.hpp, src/app/json.cpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioning_session.hpp, src/library/cose.cpp, src/library/dtls.hpp, src/library/tlv.hpp, tests/unit/test_coap_secure.cpp, tests/unit/test_dtls.cpp
* using enum class to prevent to prevent conflicts with C stuff
* adding constexpr because why not
=> [code] use enum class and some constexpr

tests/integration/bootstrap.sh
This PR fixes integration test error introduced by https://github.com/openthread/openthread/pull/4555.
=> [test] fix integration test

.travis/script.sh, script/bootstrap.sh
This PR installs latest CMake with python3-pip rather than building from source.
=> [script] install latest CMake with pip

.travis.yml, .travis/script.sh, CONTRIBUTING.md, script/clang-format, script/clang-format-check, script/make-pretty, tools/commissioner_thci/commissioner.py, tools/commissioner_thci/commissioner_ctl.py, tools/commissioner_thci/commissioner_impl.py, tools/commissioner_thci/commissionerd.py, tools/commissioner_thci/example_send_mlr.py
=> [script] sync make-pretty scripts from openthread

script/bootstrap.sh
this PR installs cmake dependency `scikit-build`, which is missing on some version of respberry Pi.
=> [script] install cmake dependencies

src/app/cli/README.md
This PR updates the stale joiner command usage in the cli readme file and adds more examples.
=> [doc] update stale cli readme

src/app/border_agent.cpp
This PR fixes addresses issue https://github.com/openthread/ot-commissioner/issues/92.
=> [border-agent] fix format of TXT values in mDNS response

include/commissioner/commissioner.hpp, src/app/file_logger.cpp, src/app/file_logger.hpp, src/library/CMakeLists.txt, src/library/coap.cpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioning_session.cpp, src/library/dtls.cpp, src/library/joiner_session.cpp, src/library/joiner_session.hpp, src/library/logging.cpp, src/library/logging.hpp, src/library/socket.cpp, src/library/socket.hpp, src/library/tlv.cpp, src/library/token_manager.cpp, src/library/udp_proxy.cpp
This PR
1. adds log region.
2. rename `CommissioningSession` to `JoinerSession`.
=> [logging] add region tag to log messages

.github/workflows/build.yml, .github/workflows/tests.yml, tests/integration/bootstrap.sh, tests/integration/common.sh
=> [github-actions] add GitHub Actions

src/library/coap_secure.hpp
Resolves https://github.com/openthread/ot-commissioner/issues/113.
=> [coaps] remove use of Socket::Reset()

src/library/coap.cpp
This PR fixes typo of counting CoAP option encoding length.
=> [coap] fix coap message option encoding length counting

include/commissioner/error.hpp, src/common/CMakeLists.txt, src/common/error.cpp, src/common/error_test.cpp
This PR adds unittest for the `Error` class.
=> [error] add unittest for Error class

src/library/commissioner_impl.cpp, src/library/dtls.cpp, src/library/joiner_session.cpp
This PR includes a fix and enhancement to logging messages:
1. replace `commissioning session` with `joiner session`;
2. Logging DTLS data length;
=> [logging] misc logging enhance / fix

.github/workflows/tests.yml
Test PR adds CLI options test to cover code in src/cli/main.cpp.
=> [tests] add CLI options tests

.github/workflows/tests.yml, src/app/border_agent.cpp, tests/etc/avahi/services/border-agent.service, tests/integration/bootstrap.sh, tests/integration/common.sh, tests/integration/test_discover.sh
This PR enhances the mDNS discovery tests
1. A full list of TXT values defined by Thread 1.2 ( and 1.1)
2. Fix the State bitmap format
=> [tests] enhance mDNS discover tests

.github/workflows/android-app-release.yml
This PR builds and uploads Android APK as artifacts.
See the failure: https://github.com/openthread/ot-commissioner/actions/runs/406484641
=> [github-action] build and upload Android APK as artifacts

tests/integration/bootstrap.sh, tests/integration/common.sh, tests/integration/run_tests.sh, tests/integration/test_announce_begin.sh, tests/integration/test_ccm.sh, tests/integration/test_cli.sh, tests/integration/test_discover.sh, tests/integration/test_energy_scan.sh, tests/integration/test_joining.sh, tests/integration/test_operational_dataset.sh, tests/integration/test_pan_id_query.sh, tests/integration/test_petition.sh
Add more verbose test output to help debug when test cases fail.
=> [tests] add debug logging

script/bootstrap.sh
=> [bootstrap] add option to skip CCM dependencies

.github/workflows/build.yml, .github/workflows/tests.yml, CMakeLists.txt, src/CMakeLists.txt
Make `Warning as error` optional and default to `OFF`.
=> [cmake] fix building error on Raspberry Pi 3B

include/commissioner/commissioner.hpp, src/app/cli/interpreter.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_impl_test.cpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp
=> [meshcop] use UDP proxy for MGMT commands

tests/integration/common.sh, tests/integration/test_announce_begin.sh, tests/integration/test_cli.sh, tests/integration/test_energy_scan.sh, tests/integration/test_joining.sh, tests/integration/test_operational_dataset.sh, tests/integration/test_pan_id_query.sh, tests/integration/test_petition.sh
Depends-On: openthread/openthread#6450
=> [border-agent] use ephemeral port

tests/integration/common.sh, tests/integration/run_tests.sh
Add timeout for debugging stuck issue.
=> [test] add timeout for calling ot-ctl

src/app/border_agent.cpp
Since we are discovering MeshCoP (`_meshcop._udp`) services in IPv4 address space,
we should always prefer the `A` record.
https://github.com/openthread/ot-commissioner/blob/cea03001ddb3493647a183c7796d560b5a6c0fc5/src/app/border_agent.cpp#L73-L74
This PR rejects `AAAA` records received in a IPv4 socket.
Addresses https://github.com/openthread/ot-br-posix/issues/809.
=> [mdns] accept only A records for IPv4 sockets

src/library/commissioner_impl.cpp, tools/commissioner_thci/commissioner.py, tools/commissioner_thci/commissioner_impl.py
The main branch should be the SoT. 
This commit merges cert changes to main.
=> Merge cert to main

src/library/commissioner_impl.cpp
`Commissioner Session ID` and `Border Agent Locator` in the `Commissioner Dataset` are read-only.
Current implementation rejects setting the Commissioner Dataset if any of the fields is present, but it
is not convenient for the caller to manually clear out those fields. This commits change the implementation
to always clear out the `Commissioner Session ID` and `Border Agent Locator` fields before sending the
`MGMT_COMM_SET.req` message to the border agent.
Fixes master CI failure https://github.com/openthread/ot-commissioner/runs/2861632149.
=> [dataset] avoid setting session ID or Border Agent Locator

.github/workflows/build.yml, .github/workflows/tests.yml, .gitmodules, script/bootstrap.sh, src/app/CMakeLists.txt, src/app/commissioner_app_test.cpp, src/app/json_test.cpp, src/common/CMakeLists.txt, src/common/address_test.cpp, src/common/error_test.cpp, src/common/utils_test.cpp, src/library/CMakeLists.txt, src/library/coap_secure_test.cpp, src/library/coap_test.cpp, src/library/commissioner_impl_test.cpp, src/library/commissioner_safe_test.cpp, src/library/cose_test.cpp, src/library/dtls_test.cpp, src/library/socket_test.cpp, src/library/token_manager_test.cpp, tests/integration/test_domain_syntax.sh, third_party/CMakeLists.txt
Remove Catch2 and use googletest exclusively.
=> [testing] remove Catch2

tests/integration/common.sh
Context: https://github.com/openthread/openthread/pull/6091
=> [tests] properly configure operational dataset

src/common/logging.hpp
define a dedicated logging region for network diagnostic.
=> [log] add a new logging region for network diagnostic functionality

src/library/joiner_session.cpp
Fixes https://github.com/openthread/ot-commissioner/issues/284
=> [thread] make Joiner Provisioning URL independently optional

src/app/cli/README.md, src/app/cli/interpreter.cpp, src/app/cli/interpreter.hpp, src/app/cli/interpreter_test.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/app/commissioner_app_dummy.cpp, src/app/commissioner_app_mock.hpp
This PR sits on top of the changes in https://github.com/openthread/ot-commissioner/pull/292, please only review the second commit.
=> [cli] add state command

src/java/commissioner.i
integrated diagnostic apis into ot-commissioner.jar
=> [swig] add the diagnostic apis into swig file
