tools/commissioner_thci/commissioner_impl.py
`make_local_commissioner` is for travis tests, `make_harness_commissioner` is for test harness. We don't want to add dependency to test harness.
=> [tools] fix Commissioner THCI dependency on pexpect

src/app/commissioner_app.cpp, src/app/commissioner_app.hpp
This PR fixes the bug that `CommissionerApp` trying to stop the internal commissioner member.
This will result in **segment fault** if creating the `CommissionerApp` instance failed (`mCommissioner` is null), just as reported in issue https://github.com/openthread/ot-commissioner/issues/7.
=> [app] fix destruction of commissioner app

tools/commissioner_thci/commissioner_impl.py
This PR includes commissioner THCI fixes from IOP12 and latest tests:
1. set tty column to 4096. A commissioner command may exceed the tty column limit (256) set by `OpenThread_Wpanctl`;
2. Fix forever-loop in `_expect(...)` and `_command(...)`;
=> [tools] add commissioner THCI fixes from IOP12 and latest tests

include/commissioner/commissioner.hpp, src/app/commissioner_app.cpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp, src/library/commissioning_session.cpp
This PR adds a new API to notify application that a joiner has been successfully commissioned:
```c++
using CommissioningHandler = std::function<void(const JoinerInfo &aJoinerInfo, Error aError)>;
virtual SetCommissionerHandler(CommissioningHandler aCommissioningHandler) = 0;
```
This addresses issue https://github.com/openthread/ot-commissioner/issues/9.
=> [api] add commissioning handler

CMakeLists.txt, src/CMakeLists.txt
This PR adds a `OT_COMM_APP`  CMake option to control building of the CLI App. This could be useful when including OT Commissioner in a project as a library.
This PR also fixes the `OT_COMM_TEST` option.
=> [build] add cmake option to disable building CLI App

src/library/CMakeLists.txt
* headers: this is important as some IDEs only show the header files if they are listed cmake script
* static: allow users to use shared libs -> default is static, can be changed to shared by passing `-DBUILD_SHARED_LIBS=ON` to cmake
=> [build] add headers and cmake and allow shared lib

tests/integration/bootstrap.sh, tests/integration/common.sh, tests/integration/run_tests.sh
This PR enhances integration test for OTBR by
- provide an environment to skip building OTBR from source.
- reduce git clone by option `--depth=1`.
- change tmp dir to `/tmp/test-ot-commissioner` to keep current dir clean.
- Add file descriptions.
Those changes enable reusing the integration test script in ot-br-posix project.
=> [tests] enhance integration test setup for OTBR

src/app/cli/interpreter.cpp, src/app/cli/interpreter.hpp, src/library/uri.hpp
This PR removes eliminates static objects with non-trivial destructor. This is to resolve the out-of-order destruction issue of those static object which may leading to bad access to already destructed objects.
=> [code] avoid static objects with non-trivial destructor

include/commissioner/commissioner.hpp, include/commissioner/error.hpp, src/app/cli/interpreter.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp, tests/unit/test_commissioner_impl.cpp
This PR returns the commissioner ID when petition failed due to an already-active commissioner in the Thread Network.
=> [petition] return ID of existing active commissioner if one exists

tests/integration/common.sh
This PR fixes the [flash initialization issue](https://github.com/openthread/openthread/issues/4722) by creating separate tmp directory for wpantund and CLI program.
=> [tests] workaround of openthread simulation flash creating issue

.gitignore, src/library/CMakeLists.txt, third_party/CMakeLists.txt, third_party/COSE-C/CMakeLists.txt
This PR enables building shared libraries with builtin CMake option `-DBUILD_SHARED_LIBS=ON`. Shared libraries are required by [Java JNI](https://en.wikipedia.org/wiki/Java_Native_Interface).
=> [build] enable building shared libraries

include/commissioner/network_data.hpp
This PR fixes a bit mask typo. It was working because it resulted in using 0x0001 for its bit mask and 0x0001 hasn't been allocated.
=> [network-data] fix bit mask

src/library/coap_secure.hpp, src/library/commissioning_session.cpp, src/library/dtls.cpp, src/library/dtls.hpp
This PR refines DTLS state and error handling:
- return `Error::kSecurity` for DTLS errors (return `Error::kTransportFailed` for net error)
- unify error casting from mbedtls result
- remove `State::kDisconnecting` state to simplify state transition
This PR addresses [issue#27](https://github.com/openthread/ot-commissioner/issues/27).
=> [dtls] refine DTLS state and error handling

include/commissioner/defines.hpp, include/commissioner/error.hpp, src/app/commissioner_app.cpp, src/app/etc/commissioner/non-ccm-config.json, src/app/json.cpp, src/common/address.cpp, src/common/address.hpp, src/common/utils.hpp, src/library/coap.cpp, src/library/commissioner_impl.cpp, src/library/commissioner_safe.cpp, src/library/commissioning_session.cpp, src/library/socket.cpp, src/library/socket.hpp, src/library/udp_proxy.cpp, tests/unit/test_coap.cpp, tests/unit/test_coap_secure.cpp, tests/unit/test_cose.cpp
This PR makes error unignorable by applying `warn_unused_result` attribute. 
When a type is annotated with `warn_unused_result` attribute, any function returns the object of this type must explicitly check(or ignore) the return value to get rid of the warning/error.
OT mimics exception with two error handling macros: `verifyOrExit` and `SuccessorExit`. But it is easy for a function calling to ignore the return error silently, resulting in escaped errors. And, when looking at a calling without checking the return error, the reader doesn't know if ignoring error is intentional or because of careless.
I think it is crutial to always explicitly handle (check or ignore) a return error, as Google's famous `Status` class (something like `Error` class here) is not ignorable.
We achieve this by:
- …
=> [error] make error unignorable

src/app/etc/commissioner/ccm-config.json
The CCM Commissioner supports using `PSKc` for establishing commissioner session, but it should not be recommended by default.
=> [config] comment out PSKc for default CCM config file

src/app/cli/interpreter.cpp
The PR updates the help document of `opdataset set securitypolicy` to make the parameters clearer.
address issue https://github.com/openthread/ot-commissioner/issues/60.
=> [cli] fix help doc of the 'opdataset set securitypolicy' command

third_party/mbedtls/CMakeLists.txt
This PR removes the redundant `CMake` compile definitions in directory of `mbedtls`, which is covered by target-based commands below:
https://github.com/openthread/ot-commissioner/blob/3740b93fcf6b6220241eb8cafd6652ee2e58c991/third_party/mbedtls/CMakeLists.txt#L43-L63
=> [mbedtls] remove redundant compile definitions

include/commissioner/commissioner.hpp, src/app/CMakeLists.txt, src/app/cli/interpreter.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/app/file_logger.cpp, src/app/file_logger.hpp, src/app/file_util.cpp, src/app/file_util.hpp, src/app/json.cpp, src/app/json.hpp, src/library/commissioner_impl.cpp, src/library/logging.cpp, src/library/logging.hpp
This PR refine the configuration and logger:
1. Defines a new `Logger` abstract class to easily customize an application-provided logger.
2. Throw exception when parsing `Network Data` and `Config` from json file failed and convert it to the commissioner `Error`. This give the chance to return user-friendly error message for the configuration file (or Network Data file) when https://github.com/openthread/ot-commissioner/pull/45 is merged.
3. Separate file utility to `file_util.cpp`.
4. Separate file logging to `file_logger.cpp`.
5. Initialize `CommissionerApp` directly with `Config` and remove the intermediate `AppConfig`. This enable unit tests for `CommissionerApp` (coming with separate PR).
=> [config]  refine commissioner configuration and logger

src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/library/commissioning_session.cpp
This way it would be possible to let every device join, no matter what kind of application layer provisioning is required later.
=> [provisioning-url] move matching to application layer

.travis/script.sh
This PR changes travis CI to use GNU make rather than ninja on Mac OS X. This PR is a workaround of a known [issue](https://github.com/ninja-build/ninja/issues/1704) with ninja on Mac OS X.
=> [travis] use GNU make for Mac OS X

.travis.yml, CONTRIBUTING.md
v0.30.0 (released on 2020-04-23) introduces formatting changes that
are not compatible with v0.29.0.
=> [pretty] fix yapf version to 0.29.0

src/app/cli/README.md, src/app/cli/interpreter.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, tests/integration/run_tests.sh, tests/integration/test_cli.sh
Instead of pull Commissioner Dataset from the Thread Network, This PR pushes a default Commissioner Dataset to the Thread Network when connected.
This changes the CLI command `network pull` to `network sync`.
=> [app] push Commissioner Dataset when connected

src/library/CMakeLists.txt, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp, src/library/commissioner_safe_test.cpp
We were directly calling [event_base_loopbreak](http://www.wangafu.net/~nickm/libevent-2.0/doxygen/html/event_8h.html#a07a7599e478e4031fa8cf52e26d8aa1e) to stop the event loop running in background thread from user thread. It has a problem that if `event_base_loopbreak` is called even before the event loop has been started (`event_base_loop` has not been called), the event loop will not be breaked (because it has not been started yet). This will result in dead loop when we stop immediately after starting the commissioner.
```text
T     user thread                                      event loop thread
----------------------------------------------------------------------------------------
t0    commissioner->Start():start event loop thread …
```
=> [event-loop] break event loop from inside

src/app/file_logger.cpp, src/common/CMakeLists.txt, src/common/time.cpp, src/common/time.hpp, src/library/CMakeLists.txt, src/library/coap.cpp, src/library/coap.hpp, src/library/coap_secure.hpp, src/library/coap_test.cpp, src/library/commissioner_impl.cpp, src/library/commissioning_session.cpp, src/library/commissioning_session.hpp, src/library/dtls.cpp, src/library/dtls.hpp, src/library/dtls_test.cpp, src/library/message.hpp, src/library/network_data.cpp, src/library/socket.cpp, src/library/socket.hpp, src/library/socket_test.cpp, src/library/timer.hpp, src/library/udp_proxy.cpp, src/library/udp_proxy.hpp
This PR fixes the issues that the `KEK TLV` is not included for only `JOIN_FIN.rsp` messages.
=> [meshcop] include KEK TLV for only JOIN_FIN.rsp message

src/app/border_agent.cpp
`:X` is not supported for string type and will throw an exception.
=> [border-agent] fix fmt usage

src/app/file_logger.cpp, src/app/file_logger.hpp, src/app/json.cpp
This PR:
1. Makes concurrent call to `FileLogger::Log(...)` safe.
2. Refactors `FileLogger` to return `Error` when construction failed.
=> [logging] make FileLogger thread safe

include/commissioner/commissioner.hpp, include/commissioner/defines.hpp, include/commissioner/network_data.hpp, src/app/cli/interpreter.cpp, src/app/commissioner_app.cpp, src/common/address.hpp, src/library/coap.cpp, src/library/commissioner_safe.cpp, src/library/dtls.cpp, src/library/endpoint.hpp, src/library/tlv.hpp, src/library/udp_proxy.hpp
OpenThread style puts C++ headers before C headers. https://github.com/openthread/openthread/blob/master/STYLE_GUIDE.md
=> [code] include C++ standard headers before C standard headers

CMakeLists.txt, src/library/CMakeLists.txt, third_party/libevent/CMakeLists.txt
This PR set the version of libevent to [2.1.11-stable](https://github.com/libevent/libevent/tree/release-2.1.11-stable).
The latest libevent master introduced pthread features ([pthread_mutexattr_setprotocol](https://www.gnu.org/software/gnulib/manual/html_node/pthread_005fmutexattr_005fsetprotocol.html)) that are not supported on Android 5 (API level = 21).
=> [third-party] use libevent 2.1.11-stable

src/app/commissioner_app.cpp, src/app/commissioner_app.hpp
This PR clears data associated with the connected Thread Network when the commissioner is stopped (disconnected from the Thread Network).
=> [app] clear network data when stopped

src/app/cli/interpreter.cpp, src/app/commissioner_app.cpp, src/app/file_logger.cpp, src/app/json.cpp, src/common/address.cpp, src/common/utils.cpp, src/common/utils.hpp, src/library/coap.cpp, src/library/coap.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_safe.cpp, src/library/commissioning_session.cpp, src/library/cose.cpp, src/library/dtls.cpp, src/library/error.cpp, src/library/network_data.cpp, src/library/socket.cpp, src/library/socket_test.cpp, src/library/timer.hpp, src/library/tlv.cpp, src/library/token_manager.cpp, src/library/udp_proxy.cpp
This PR renames macro `ASSSERT` to `VerifyOrDie`.
See https://github.com/openthread/ot-commissioner/pull/84#discussion_r415919644 for backgrounds.
=> [utils] rename 'ASSERT' to 'VerifyOrDie'

include/commissioner/commissioner.hpp, src/app/commissioner_app.cpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe_test.cpp
This PR changes API `Commissioner::Create` to propagate initialization errors.
=> [api] propagate Commissioner construction errors

include/commissioner/commissioner.hpp, src/app/cli/interpreter.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_impl_test.cpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp, src/library/commissioner_safe_test.cpp, src/library/joiner_session.cpp, src/library/joiner_session.hpp
This PR refactors commissioner handlers to use a `CommissionerHandler` interface for handling all commissioner events. An application should implement the `CommisssionerHandler` interface to handle those events.
Change summary:
- use `CommissionerHandler` interface to handle commissioner events.
- add `OnJoinerConnected` to handle joiner DTLS connection event. This addresses issue https://github.com/openthread/ot-commissioner/issues/28.
- add `OnKeepAliveResponse`  to notify whether the commissioner was rejected or not.
- remove `JoinerType` and `JoinerInfo` from public library interface.
This PR supports Java binding of the commissioner library.
=> [api] refactor commissioner handlers

include/commissioner/defines.hpp, src/app/CMakeLists.txt, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/app/commissioner_app_test.cpp, src/library/commissioner_impl.cpp, tests/integration/common.sh, tests/integration/test_joining.sh
This PR addes validation of joiner PSKd to force it conform to the Thread Spec. It also changes PSKd from `ByteArray` to `std::string` since PSKd can be only digits and uppercase chars.
related comments: https://github.com/openthread/ot-commissioner/pull/72#discussion_r409654671
=> [joiner] validate joiner PSKd

include/commissioner/commissioner.hpp, src/app/commissioner_app.cpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp
This PR removes API `start` and `stop`. Those two APIs are specific to event loop thread, which should be hide behind the public interface.
=> [api] remove API 'start' and 'stop'

src/app/json.cpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp
This PR removes all `throws` but keep only `SuccessOrThrow` in `json.cpp`, since the json library uses `exception` exclusively.
By searching `throw` in `src`, it gives only one match in [json.cpp](https://github.com/openthread/ot-commissioner/blob/560e6025d30390999ead96f1f3deda78bf5e5ee1/src/app/json.cpp#L83) (called by `SuccessOrThrow`).
https://github.com/openthread/ot-commissioner/blob/560e6025d30390999ead96f1f3deda78bf5e5ee1/src/app/json.cpp#L78-L85
=> [code] remove throws

tests/integration/bootstrap.sh, tests/integration/common.sh, tests/integration/run_tests.sh, tests/integration/test_announce_begin.sh, tests/integration/test_cli.sh, tests/integration/test_discover.sh, tests/integration/test_energy_scan.sh, tests/integration/test_joining.sh, tests/integration/test_operational_dataset.sh, tests/integration/test_pan_id_query.sh, tests/integration/test_petition.sh
This PR fixes integration tests with OTBR 0.2 which deprecated wpantund.
=> [tests] fix integration tests with OTBR 0.2

tests/integration/common.sh
OTBR has just switched to use radi-url (https://github.com/openthread/ot-br-posix/pull/448) which breaks integration tests here.
This PR addresses this issue.
=> [tests] fix integration tests with otbr

src/library/token_manager.cpp
This PR addresses issue https://github.com/openthread/ot-commissioner/issues/42 that the Commissioner Token will be cleared when failed to set it by re-extracting the Token into a CBOR object after accepting the signed raw token.
=> [ccm] fix setting Commissioner Token

src/library/dtls.cpp, src/library/socket.cpp, src/library/socket.hpp
The `DtlsSession` was trying to reset the `Socket` when disconnected but it shouldn't. Because the socket is not connected/bound by `DtlsSession`, so it should not be reset by `DtlsSession` as well.
- removes resetting socket in `DtlsSession::Disconnect()` and remove `Socket::Reset()`.
- Frees socket fd when before connecting and binding to allow multiple calls to `Connect` and `Bind`.
=> [socket] remove Socket::Reset() API

CMakeLists.txt
According to https://semver.org/, version `1.0.0` defines the stable public API. But we are currently changing the public API frequently and this situation may continue before we finishing building Commissioner Service with ot-commissioner.
This PR resets the version to `0.1.0` to indicates that the public API is not stable.
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.
=> [cmake] reset version to 0.1.0

src/library/dtls.cpp
This PR fixes DTLS events handling when the session is disconnected. Previous implementation has the assumption that the underlying socket will be closed when the session is disconnected. But with PR https://github.com/openthread/ot-commissioner/pull/110,  the socket now may be open in this case.
This PR ignores the incoming data when the DTLS session is disconnected.
=> [dtls] handle events when disconnected

src/library/coap.cpp, src/library/coap_test.cpp, tools/commissioner_thci/commissioner_impl.py
This PR addresses several LGTM.com comments:
1. remove meaningless unsigned comparison to zero.
2. remove unused python imports.
3. add TODO to URI path option unittest.
=> [code] address LGTM.com comments

src/app/cli/interpreter.cpp
This PR
1. fixes the output of the `help` command (it gave no command list).
2. returns `INVALID_COMMAND` for invalid commands.
=> [cli] fix CLI commands output

include/commissioner/defines.hpp
`size_t` is not defined in some raspberry pi devices with gcc 6.
This PR includes `<stddef.h>` for definition of `size_t`.
=> [api] add missing header for definition of size_t

src/library/socket.cpp
The `Connect` and `Bind` methods are reentrant, we should delete the associated event struct if it has already been added to the event loop.
=> [socket] fix deleting socket event when reconnect or rebind

tests/integration/bootstrap.sh, tests/integration/common.sh
This allows users to specify a custom OpenThread directory so that we can include external commissioner tests as a part of OpenThread CI.
=> [test] enable custom OpenThread path

tests/integration/bootstrap.sh, tests/integration/common.sh, tests/integration/test_announce_begin.sh, tests/integration/test_cli.sh, tests/integration/test_discover.sh, tests/integration/test_energy_scan.sh, tests/integration/test_joining.sh, tests/integration/test_operational_dataset.sh, tests/integration/test_pan_id_query.sh, tests/integration/test_petition.sh
When running tests, this makes the `otbr` to be built with `openthread` provided by environment variables so changes from `openthread` PRs can be correctly applied.
Also changes `killall -9` to `killall` to prevent the loss of coverage data.
=> [test] use provided openthread repo for otbr

.github/workflows/tests.yml, CMakeLists.txt, src/library/CMakeLists.txt, src/library/cbor.cpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/cose.cpp, src/library/cose.hpp, src/library/cose_test.cpp, src/library/cwt.hpp, src/library/token_manager.cpp, src/library/token_manager.hpp, src/library/token_manager_test.cpp, third_party/CMakeLists.txt
This PR adds a CMake option `OT_COMM_CCM` and feature switch `OT_COMM_CONFIG_CCM_ENABLE` to turn off Commercial Commissioning Mode support. It has the benefits of increasing code coverage and remove unnecessary dependencies (cn-cbor, COSE-C) when `CCM` features is not needed.
=> [ccm] add compile-time option to exclude CCM features

src/library/commissioner_safe.cpp, src/library/joiner_session.cpp, src/library/socket_test.cpp
This PR has two small fixes
1. Add a timeout value for the async call event so that the event loop will not exit because of no events.
2. User triggered event struct (with fd equals -1) should not listen on READ, WRITE events.
=> [event] fix ading user triggered events

.github/workflows/tests.yml, tests/integration/bootstrap.sh, tests/integration/common.sh, tests/integration/run_tests.sh, tests/integration/test_announce_begin.sh, tests/integration/test_cli.sh, tests/integration/test_discover.sh, tests/integration/test_energy_scan.sh, tests/integration/test_joining.sh, tests/integration/test_operational_dataset.sh, tests/integration/test_pan_id_query.sh, tests/integration/test_petition.sh
This removes the dependency of `ot-br` in integration tests.
=> [test] replace ot-br with ot-daemon in integration tests

script/bootstrap.sh
This PR removes the commands to enable IPv6 forwarding which is not necessary for ot-commissioner.
=> [scripts] remove unnecessary commands in bootstrap script

include/commissioner/commissioner.hpp, src/app/cli/README.md, src/app/cli/interpreter.cpp, src/app/cli/interpreter.hpp, src/app/cli/main.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/library/coap.cpp, src/library/coap.hpp, src/library/coap_secure.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp, src/library/joiner_session.cpp, src/library/joiner_session.hpp, src/library/token_manager.hpp, src/library/udp_proxy.hpp
This PR rename the API `AbortRequests` to `CancelRequests`, it season to be more reasonable to name it `CANCEL` than `ABORT` when it is the user invoking it:
```C++
/**
* The operation was cancelled (typically by the caller).
*/
kCancelled = 1,
/**
* The operation, transaction or message exchange was aborted.
*/
kAborted = 14,
```
=> [api] rename API AbortRequests to CancelRequests

src/app/cli/CMakeLists.txt, src/app/cli/main.cpp
Synchronization primitives (std::mutex, std::future) in namespace `std` are used to synchronize calls to the commissioner API. Unfortunately, those synchronization primitives are not [signal-safe](https://man7.org/linux/man-pages/man7/signal-safety.7.html) and will result in deadlock.
This PR fixes this by using a dedicated thread to wait for the signal.
=> [cli] fix signal handling

.github/workflows/build.yml, .github/workflows/tests.yml, CMakeLists.txt, script/bootstrap.sh, src/app/CMakeLists.txt, src/app/cli/CMakeLists.txt, src/common/CMakeLists.txt, src/library/CMakeLists.txt, third_party/CMakeLists.txt
This PR
1. changes the minimum required CMake version from `3.13.1` to `3.10.1` since many platforms (ubuntu, android studio) have 3.10.X as the default CMake version
2. submodule `mdns` is updated to support this change
3. avoid inclusion of unnecessary third parties
=> [cmake] lower minimum cmake version

CMakeLists.txt, src/java/CMakeLists.txt
This PR adds a new option `OT_COMM_JAVA_BINDING_OUTDIR` to allow the user specify the output directory of auto-generated java files. This eases integration with Android applications.
=> [java] output generated java source files to given directory

src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, tests/integration/common.sh, tests/integration/run_tests.sh, tests/integration/test_ccm.sh
This PR increases code coverage of CLI application:
1. Add CCM tests to cover CLI commands.
2. group CCM features together.
3. remove duplicate error checking in commissioner_app.
=> [tests] add CCM tests

README.md, src/app/cli/README.md
We have the build and configuration steps in the CLI readme document before we have the page at [openthread.io](https://openthread.google.cn/guides/commissioner).
This PR points OT Commissioner CLI build and configuration to the page at [openthread.io](https://openthread.google.cn/guides/commissioner/build).
=> [doc] remove build & configuration instructions from CLI readme

include/commissioner/commissioner.hpp, include/commissioner/network_data.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp
Parsing the Active Operational Dataset into `struct ActiveOperationalDataset` is for manipulating each field of the dataset and the commissioner app doesn't need to write a decoder by their own. But the commissioner app may store or transfer Active Operational Dataset as a byte array. It would be convenient to have the raw TLV format of the dataset so that the commissioner app doesn't need to write an encoder by their own.
This PR adds a new APIs (`GetRawActiveDataset(...)`) to return raw Active Operational Dataset.
=> [active-dataset] returns raw Active Operational Dataset TLVs

src/java/commissioner.i
We forgot to ignore the async version of the `GetRawActiveDataset()` API introduced by https://github.com/openthread/ot-commissioner/pull/142, this PR fixes this.
Background: we currently supports only the sync version of all OT Commissioner APIs.
=> [java] ignore async GetRawActiveDataset API for java binding

src/library/commissioner_impl.cpp, tools/commissioner_thci/commissioner.py, tools/commissioner_thci/commissioner_impl.py
This PR dumps `MLR.rsp` payload to the log and adds new THCI API (`getMlrLogs`) to query MLR logs for use of 1.2 certification.
=> [cert] dump MLR.rsp payload for 1.2 certification

src/library/commissioner_impl.cpp
This PR fixes commissioner state transition when we failed to send the Keep-Alive message:
1. disconnect from the Border Agent.
2. Set the commissioner state to `kDisabled` when disconnected.
=> [library] fix commissioner state when sending keep-alive failed

src/java/commissioner.i
This PR helps SWIG to map Java `byte` to/from C++ `uint8_t` when it is used for `std::vector<uint8_t>`.
SWIG by default maps Java `short` to/from C++ `uint8_t` because Java `byte` is a signed integer that cannot hold all values of `uint8_t`. But when it comes to a byte array, it doesn't matter whether it is signed or unsigned and we'd like to map `uint8_t`  to/from Java `byte` because they have the same width.
**The CHIP PR https://github.com/project-chip/connectedhomeip/pull/2492 depends on this (see the [discussion](https://github.com/project-chip/connectedhomeip/pull/2492#discussion_r503060646))**.
=> [swig] map Java byte to uin8_t for only the ByteArray class

.github/workflows/build.yml, include/commissioner/defines.hpp, include/commissioner/network_data.hpp, script/bootstrap.sh, src/java/CMakeLists.txt, src/java/commissioner.i
This PR includes misc updates/fixes for bootstrapping:
1. downgrade required SWIG version to 3.0 since this is the default version that package tools have for Linux;
2. install SWIG in the bootstrap script;
3. install `python3` setup tools instead of `python2` since it is deprecated;
=> [scripts] misc fixes in bootstrap script

.github/workflows/build.yml, include/commissioner/defines.hpp, include/commissioner/network_data.hpp, script/bootstrap.sh, src/java/CMakeLists.txt
This PR reverts our changes of downgrading minimum SWIG version to 3.0 in #152.
We did downgrade the minimum version for easy installation of SWIG on old Linux distributions. But the incoming Commissioner Android App relies on the Java methods generated by SWIG 4.0. Unfortunately, we didn't have a GH job to test the SWIG-generated Java code for now, but it will come with the Android App PR.
=> [swig] revert changes to the minimum SWIG version

.github/workflows/build.yml, CONTRIBUTING.md, script/bootstrap.sh, script/clang-format
This PR downgrades `clang-format` to `9.0` given that `llvm@10` is not available in brew repository. Instead of failing the bootstrap script, we changed to tolerate failure of installing `clang-format`.
related issue: https://github.com/openthread/openthread/issues/5724
=> [script] downgrade to clang-format-9

script/bootstrap.sh, tests/integration/bootstrap.sh
This PR cleans stale dependencies that is no longer required to build the default OT Commissioner library and CLI.
Fixes #154
=> [script] remove unused bootstrap dependencies

src/library/coap.cpp, src/library/coap.hpp
This PR has two fixes to the CoAP retransmission of confirmable requests:
1. Stop the retransmission timer when all requests are cleared.
2. Start the retransmission timer when there are queueing requests that are waiting for responses.
=> [coap] fix retransmission of confirmable CoAP requests

.github/workflows/android-app-release.yml
We was creating APK artifacts for release on a pull request (and the APK is created only when the pull request has a name format of `android-release/x.x.x`). But we should create the release APK from master.
This PR changes to build the APK from master and uploads the artifact for only `push` events.
=> [github-action] create APK artifacts on master branch

src/library/commissioner_impl.cpp
1. The Pending Dataset check is wrong: the bitwise or (`| `) should be bitwise and (`&`)
2. Both Pending and Active Dataset Get response checks are too restrict.
The Commissioner CLI always sends MGMT_ACTIVE/PENDING_GET.req for all TLVs even when only a single TLV is requested by the user and thus current implementation is working.
=> [dataset] fix and relax dataset response check

src/library/commissioner_impl.cpp
I missed the `MGMT_COMMISSIONER_SET.req` and `MGMT_COMMISSIONER_GET.req` which should also be sent via UDP proxy.
=> [mgmt] send MGMT_COMMISSIONER_GET/SET.req with UDP proxy

src/library/commissioner_impl.cpp
Current implementation invokes `OnJoinerRequest` for every joiner message exchanges. This will result in the user be notified multiple times for the same joiner connection.
This commits changes to invoke `OnJoinerRequest` for the first message of a joiner connection.
=> [joiner-session] invoke "OnJoinerRequest" for the first joiner message

src/app/cli/CMakeLists.txt, src/common/CMakeLists.txt, src/library/CMakeLists.txt
This commit includes two small changes:
1. Install static library dependencies
2. Install `commissioner-common`: applications need to link against both `commissioner` and `commissioner-common`.
3. remove unused linking of `ncurses`.
=> [cmake] install with static library dependencies

include/commissioner/commissioner.hpp, include/commissioner/defines.hpp, src/app/commissioner_app.cpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp, src/library/udp_proxy.cpp, src/library/udp_proxy.hpp
Previous implementation requires the caller of the Commissioner library to set Mesh-Local prefix before
initiating `MGMT` commands. it is error-prone and breaks backward compatibility: we need to first fetch
the Active Operational Dataset and set the Mesh-Local Prefix to the commissioner library before sending
other `MGMT_*` commands:
https://github.com/openthread/ot-commissioner/blob/1b5dd47875fdd52e86dd6334973c36fa9e1ba899/src/app/commissioner_app.cpp#L151-L155
This PR refactors the UDP Proxy to have it manage the Mesh-Local prefix inside the `ProxyClient` class.
1. The Mesh-Local prefix is lazily requested from the Border Agent  before sending the first `MGMT` command (if no Mesh-Local prefix is cached).
2. The cached Mesh-Local prefix is cleared when the commissioner receives …
=> [udp-proxy] track Mesh-Local prefix in UDP Proxy client

tests/integration/common.sh, tests/integration/run_tests.sh, tests/integration/test_native_commissioner.sh
This commit adds a test for ot-commissioner acting as a native commissioner.
Depends-On: openthread/openthread#6541
=> [test] native commissioner

CMakeLists.txt, include/commissioner/commissioner.hpp, src/app/cli/CMakeLists.txt, src/app/cli/main.cpp, src/library/CMakeLists.txt, src/library/commissioner_impl.cpp
This commit adds a new commissioner `API` that returns the commissioner version.
Also add git revision to the version string.
=> [api] add API for getting commissioner version

CMakeLists.txt, src/app/CMakeLists.txt, src/app/cli/interpreter.cpp, src/app/cli/interpreter.hpp, src/app/cli/main.cpp, src/app/logger_util.hpp, src/app/sys_logger.cpp, src/app/sys_logger.hpp, tests/integration/test_joining.sh, tools/commissioner_thci/commissioner_ctl.py
This PR includes two small enhancements:
1. Support starting the `commissioner-cli` without specifying a configuration file.
a. pskc is set to all-one.
b. log messages are printed to syslog (/var/log/syslog).
2. Add sys logger support.
=> [cli] support default config without specifying a config file

src/app/cli/README.md, src/app/commissioner_app.cpp
This commit adds the CLI documentation of the `borderagent discover` command.
Also fixes a bug for the `borderagent get locator` command that the locator is not
pulled to the commissioner.
=> [cli] fix "borderagent" command documentation

tests/integration/common.sh
The CLI command `masterkey` has been changed to `networkkey`.
=> [testing] replace `masterkey` with `networkkey`

tools/commissioner_thci/commissioner_impl.py
Make sure Commissioner logs are clean at the beginning of each test.
=> [thci] flush logs in between tests

tests/integration/common.sh
This commit increases the wait time for leader start. This is to
address the changes in behavior in Thread spec related to the
number of MLE Parent Request messages that device needs to send in
the first attach attempt before it can become leader.  The new design
requires a device to send a total of six Parent Request messages,
first two to routers followed by four to routers and REEDs, each
having its own corresponding wait time.
=> [test] increase wait time for leader start

tests/integration/test_native_commissioner.sh
This commit increases the wait time for leader start. This is to
address the changes in behavior in Thread spec related to the
number of MLE Parent Request messages that device needs to send in
the first attach attempt before it can become leader.  The new design
requires a device to send a total of six Parent Request messages,
first two to routers followed by four to routers and REEDs, each
having its own corresponding wait time.
=> [test] update leader start in `test_native_commissioner()`

.github/workflows/android-app-build.yml, .github/workflows/android-app-release.yml, .github/workflows/build.yml
1. `android/sdk/ndk-bundle` was moved to `android/sdk/ndk/$API`
2. macos-10.15 was deprecated by macos-12
=> [build] fix Android builds

.github/workflows/build.yml, CMakeLists.txt
`pthread` is already included in Android glibc implementation (`bionic`), so there
is no necessary to find the thread libs separately.
Reference: https://stackoverflow.com/questions/5990661/cmake-find-packagethreads-for-android-cross-compilation
=> [ci] fix cannot find Threads on Android

tools/commissioner_thci/commissioner_impl.py
Change format string introduced in python 3 to python 2 compatible 'format' function.
=> [thci] change python format string to format function

tests/integration/test_native_commissioner.sh
=> [tests] properly configure operational dataset

android/BUILDING.md
The guide doc is outdated on the NDK part.
Fixes https://github.com/openthread/ot-commissioner/issues/243
=> [docs] update the Android build guide to set up NDK

android/openthread_commissioner/settings.gradle
To fix the gradle error on some platforms:
```
java.lang.IllegalStateException: Module entity with name: openthread_commissioner.app should be available
```
=> [android] make gradle rootProject.name match the project dir

.github/workflows/build.yml, CMakeLists.txt, script/bootstrap.sh, src/java/CMakeLists.txt
Updates cmake to 3.20.1 which adds support for USE_SWIG_DEPENDENCIES
USE_SWIG_DEPENDENCIES is needed to tell SWIG compiler to rebuild the java
library when the dependencies are changed. For example, we currently have a problem
that the java library is not updated even a new API is added to commissioner.hpp
=> [build] update cmake to 3.20.1

src/app/border_agent_functions_mock.cpp, src/app/border_agent_functions_mock.hpp, src/app/br_discover.cpp, src/app/br_discover.hpp, src/app/cli/README.md, src/app/cli/interpreter.cpp, src/app/cli/interpreter_test.cpp
Within the OTBR practice application, the BR host will have several interfaces. When users want to discover the border agent using mDNS, they'll need to choose the specific interface the border agent is bound to.
This change introduces a new option for the CLI command `borderagent dicover`. Users can now specify a network interface using the syntax `borderagent discover <timeout> <network interface>`. The chosen interface will be used for mDNS binding through socket options.
=> [cli] update `borderagent discover` to allow network interface selection for mDNS binding

src/app/cli/interpreter.cpp
A previously introduced macro `SO_BINDOTDEVICE`, intended to pass the pre-commit code checks, which is conflicted with an definition in header file named <sys/socket.h>. So we need remove the macro from the interpreter module. To ensure the pre-commit code checks pass, we need to include the approriate header file and call `setsocketopt` with OS-specific parameters.
=> [cli] remove definition of `SO_BINDTODEVICE` from interpreter module

.gitignore, src/app/cli/interpreter_test.cpp, src/app/cli/job_manager_test.cpp, src/app/ps/persistent_storage_json_test.cpp, src/app/ps/registry_test.cpp
Current unit tests are writing intermediate testing files to current dir.
This is polluting the source dir when executing the tests in the source root dir.
This commit updates the unit tests to output the testing data files to a dedicated
./tmp dir and ignore dir tmp/ from git.
Fixes https://github.com/openthread/ot-commissioner/issues/253
=> [test] write test files to ./tmp

src/library/uri.hpp
In order to enable libotcommissioner.jar to support the diagnostic commands, it is necessary to integrate all diagnostic URIs into the uri module.
=> [uri] add DIAG_GET URIs for disgnostic APIs

include/commissioner/defines.hpp, src/library/commissioner_impl.cpp, src/library/udp_proxy.cpp, src/library/udp_proxy.hpp
Currently, while the commissioner is transmitting udp_tx messages, the UDP source port is provided by the `DtlsSession` interface. This value is randomly generated. However, the CoAP layer on the border router side performs checks on the received udp_tx port to ensure that the destination UDP port used to outgoing messages matches the source port of the received messages. This leads to the commissioner's ACK messages not being processed, causing the BR side to repeatedly retransmit the same udp_rx message.
To resolve this issue, we use the default MM port as the only supported destination port for UDP_RX messages
=> [udp-proxy] set local port to dedicated port number(:mm) for udp proxy transaction

src/library/coap.cpp, src/library/coap_test.cpp
There could be potential out of bound error if the token length in CoAP header is zero (`&aBuf[offset]` could be referring to the next element after the end of the buffer).
Note that the added test can pass without the fix in coap.cpp but it's probably because the toolchain has some optimization to avoid such issues...
=> [coap] handle zero coap token length

src/java/commissioner.i
The commissioner.i file is behind the APIs in include/commissioner/.
Also ignores `PrintTo` given it's only for googletest.
=> [swig] fix the SWIG ignores for java

src/library/tlv.cpp, src/library/tlv.hpp
libotcommissioner.jar, a versatile Java library, provides support for wide range of TMF message transactions, including MeshCop protocols and diagnostic TLVs. This PR focuses on integrating all the diagnostic TLVs, as defined in the spec `10.11.3` into the library's TLV modulei
=> [tlv] add new tlvs for network diagnostic

.github/workflows/android-app-build.yml, android/openthread_commissioner/service/build.gradle, android/openthread_commissioner/service/src/androidTest/java/io/openthread/commissioner/ActiveOperationalDatasetTest.java
When the SWIG interface file (commissioner.i) is updated, the generated
java library API may be broken. There are currently no tests to guard this.
This commit adds a basic androidTest for this purpose. Note that an
Android rather than junit test is added because the test case depends on
an JNI library (and it's easier to work with JNI in Android tests).
=> [android] add basic tests for auto generated java lib

src/library/token_manager.cpp
There's a recent build failure of ot-reference-release when trying to bump the `ot-commissioner` repo: https://github.com/openthread/ot-reference-release/actions/runs/10164731867/job/28110844136?pr=79.
I also reproduced the issue locally. After including `common/logging.hpp`, the build is fixed.
=> [build] include `common/logging.hpp` at `token_manager.cpp` to fix build

include/commissioner/commissioner.hpp, src/app/cli/README.md, src/app/cli/interpreter.cpp, src/app/cli/interpreter_test.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/app/commissioner_app_dummy.cpp, src/app/commissioner_app_mock.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp
With '--connect-only' option, only establish secure session without attempting to petition to become active commissioner.
=> [cli] extend start command to support --connect-only option

android/openthread_commissioner/app/build.gradle, android/openthread_commissioner/app/src/main/java/io/openthread/commissioner/app/BorderAgentDiscoverer.java, android/openthread_commissioner/app/src/main/java/io/openthread/commissioner/app/BorderAgentInfo.java
On Android devices before Android U, the scope ID of Ipv6 link-local address is not set when it's returned to the caller via NsdServiceInfo. To make the LLA usable, this commit sets the missing scope ID to the interface ID of the current active default network.
=> [android] handles unscoped ipv6 link-local address

.github/workflows/android-app-build.yml, .github/workflows/android-app-release.yml, .github/workflows/build.yml, script/bootstrap.sh
-  Update upload-artifact version from v2 to v4 for handling the build-release check failure:
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`.
Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
- Update the ANDROID_NDK_HOME setting for fixing the build apk failure
ANDROID_NDK_HOME not set! Please set it to your Android NDK location!
Error: Process completed with exit code 1.
-  Install coreutils for realpath tool on MacOS for "macos" check failure
script/bootstrap.sh: line 138: realpath: command not found
=> [github-actions] fix existing checks failures due to workflows settings

include/commissioner/network_diag_data.hpp, src/library/CMakeLists.txt, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_impl_internal.hpp, src/library/commissioner_impl_test.cpp, src/library/tlv.cpp, src/library/tlv.hpp
supported TLVs:
- Ipv6addressList
- ChildIpv6AddressList
- Mode
- ChildTable
- LeaderData
- Route64
- MacCounters
- Eui64
- ExtMacAddress
- MacAddress
=> [diag] add network diagnostic data definition and parsing

include/commissioner/commissioner.hpp, src/app/cli/interpreter.cpp, src/app/commissioner_app.cpp, src/app/commissioner_app.hpp, src/app/commissioner_app_dummy.cpp, src/app/commissioner_app_mock.hpp, src/app/json.cpp, src/app/json.hpp, src/library/commissioner_impl.cpp, src/library/commissioner_impl.hpp, src/library/commissioner_safe.cpp, src/library/commissioner_safe.hpp, tests/integration/test_cli.sh
This PR adds DIAG_RST notify command into the commissioner module, allowing users to reset MacCounters(9) TLV from a peer Thread device by settting the device's mesh local address and TLV mask bits flag.
Test:
>> config set pskc 445f2b5ca6f2a93a55ce570a70efeecb
[done]
>> start 192.168.9.2 49154
[done]
> netdiag reset maccounters
[done]
>> netdiag query maccounters
Peer Address: fda1:7966:fc90:d97:0:ff:fe00:bc00
Content: {
"MacCounters": "{\n    \"IfInBroadcastPkts\": 0,\n    \"IfInDiscards\": 0,\n    \"IfInErrors\": 0,\n    \"IfInUcastPkts\": 0,\n    \"IfInUnknownProtos\": 0,\n    \"IfOutBroadcastPkts\": 2,\n    \"IfOutDiscards\": 0,\n    \"IfOutErrors\": 0,\n    \"IfOutUcastPkts\": 0\n}"
}
[done]
=> [api] enable DIAG_RST notify funcation into commissioner

.github/workflows/android-app-build.yml, .github/workflows/build.yml, android/build-commissioner-libs.sh, script/bootstrap.sh, tests/integration/common.sh
The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15.
For more details, see https://github.com/actions/runner-images/issues/10721
In addition, removed the -s option because the -s option is not supported by the realpath command in macOS 13 (Ventura) and later versions, and change the `swig@4` to `swig` due to no available formula with the name "swig@4" in macOS13.
=> [github-action] build jobs failure due to deprecated macOS-12 environment

tools/commissioner_thci/commissioner.py, tools/commissioner_thci/commissioner_ctl.py, tools/commissioner_thci/commissioner_impl.py, tools/commissioner_thci/commissionerd.py, tools/commissioner_thci/example_send_mlr.py
Migrate commissioner_thci scripts to Python 3;
Use the 2to3 tool for python2 to python3 conversion
Use flynt to convert .format(...) style string formatting to the modern f-strings
=> [thci] convert Python2 script to Python3

tools/commissioner_thci/commissionerd.service
After https://github.com/openthread/ot-commissioner/pull/310 this repo should be compatible with python3 so all python2 occurrences should be removed. 
The only occurrence is in `commissionerd.service` that it launches the service using python2. 
With this PR we can further get rid of python2 occurrences in ot-reference-release repo.
=> [python] remove the occurrence of python2 in the repo

tests/integration/common.sh, tools/commissioner_thci/commissionerd.service
There are places in the repo that uses `python <script>` command to execute the code. This can cause problems when there's python2 interpreter available on the device because the code is for python3 only. This already happens on the OS of ot-reference-release because the image is too old and python2 is still available on that one. 
While there's still a distance before ot-reference-release can migrate to a newer image, we need to fix it here.
This PR also contains the commit of https://github.com/openthread/ot-commissioner/pull/316.
=> [python] explicitly specify python3 as the python interpreter

include/commissioner/commissioner.hpp, src/library/commissioner_impl.cpp
This pull request refactors the handling of commissioner resignation and keep-alive messages. The logic for disconnecting after sending a "Reject" keep-alive message is now correctly handled in the response callback.
=> [meshcop] refactor commissioner resign and keep alive handling logic
